version: '3.8'

services:
  buytoken-backend:
    build:
      context: buytoken-backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  electricity-testing:
    build:
      context: electricity-testing
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: igiraneza
      MONGO_INITDB_ROOT_PASSWORD: igiraneza123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: igiraneza
      ME_CONFIG_MONGODB_ADMINPASSWORD: igiraneza123
      ME_CONFIG_MONGODB_URL: mongodb://igiraneza:igiraneza123@mongo:27017/
      
    volumes:
      - db:/var/lib/mongodb/data
volumes:
  db:
